<?php

return [
    'paths' => ['api/*', 'email-verify', 'sanctum/csrf-cookie'],
    'allowed_methods' => ['*'],
    'allowed_origins' => [
        'https://skills-api.comfarnet.org',
        'https://skills.comfarnet.org',
        'comfarnet.org',
        'http://localhost',
        'https://skills-ug.8technologies.net',
        'https://skills-ug.8technologies.net',
        'http://skills-ug.8technologies.net',
        'skills-ug.8technologies.net',
        'http://localhost:5173',
        'https://www.8jobspot.com',
        'http://www.8jobspot.com',
        'https://8jobspot.com',
        'http://8jobspot.com',
        '8jobspot.com',
    ],
    'allowed_origins_patterns' => [
        'https://skills-api.comfarnet.org',
        'https://skills.comfarnet.org',
        'comfarnet.org',
        'http://localhost',
        'https://skills-ug.8technologies.net',
        'https://skills-ug.8technologies.net',
        'http://skills-ug.8technologies.net',
        'skills-ug.8technologies.net',
        'http://localhost:5173',
        'https://www.8jobspot.com',
        'https://8jobspot.com',
        '8jobspot.com',
    ],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => false,
];
