<?php

namespace App\Admin\Controllers;

use App\Models\User;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Show;

class SystemUsersController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = 'User';

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new User());
        $grid->model()->orderBy('id', 'desc');
        $grid->quickSearch('name', 'email', 'phone_number_1', 'phone_number_2', 'national_id_number', 'passport_number', 'tin', 'nssf_number', 'bank_account_number', 'company_name', 'company_trade_license_no', 'company_tax_id', 'company_website_url', 'company__email', 'company__phone', 'company_facebook_url', 'company_linkedin_url', 'company_operating_hours', 'company_certifications', 'company_ownership_type', 'company_status', 'company_country', 'company_address', 'company_phone_number', 'company_description', 'company_logo', 'company_year_of_establishment', 'company_employees_range', 'company_has_accessibility', 'company_has_disability_inclusion_policy', 'company_district_id', 'company_sub_county_id', 'company_main_category_id', 'company_sub_category_id', 'company_name', 'company_year_of_establishment');

        $grid->column('id', __('Id'));
        $grid->column('username', __('Username'));
        $grid->column('password', __('Password'));
        $grid->column('name', __('Name'));
        $grid->column('avatar', __('Avatar'));
        $grid->column('remember_token', __('Remember token'));
        $grid->column('created_at', __('Created at'));
        $grid->column('updated_at', __('Updated at'));
        $grid->column('enterprise_id', __('Enterprise id'));
        $grid->column('first_name', __('First name'));
        $grid->column('last_name', __('Last name'));
        $grid->column('date_of_birth', __('Date of birth'));
        $grid->column('place_of_birth', __('Place of birth'));
        $grid->column('sex', __('Sex'));
        $grid->column('home_address', __('Home address'));
        $grid->column('current_address', __('Current address'));
        $grid->column('phone_number_1', __('Phone number 1'));
        $grid->column('phone_number_2', __('Phone number 2'));
        $grid->column('email', __('Email'));
        $grid->column('nationality', __('Nationality'));
        $grid->column('religion', __('Religion'));
        $grid->column('spouse_name', __('Spouse name'));
        $grid->column('spouse_phone', __('Spouse phone'));
        $grid->column('father_name', __('Father name'));
        $grid->column('father_phone', __('Father phone'));
        $grid->column('mother_name', __('Mother name'));
        $grid->column('mother_phone', __('Mother phone'));
        $grid->column('languages', __('Languages'));
        $grid->column('emergency_person_name', __('Emergency person name'));
        $grid->column('emergency_person_phone', __('Emergency person phone'));
        $grid->column('national_id_number', __('National id number'));
        $grid->column('passport_number', __('Passport number'));
        $grid->column('tin', __('Tin'));
        $grid->column('nssf_number', __('Nssf number'));
        $grid->column('bank_name', __('Bank name'));
        $grid->column('bank_account_number', __('Bank account number'));
        $grid->column('primary_school_name', __('Primary school name'));
        $grid->column('primary_school_year_graduated', __('Primary school year graduated'));
        $grid->column('seconday_school_name', __('Seconday school name'));
        $grid->column('seconday_school_year_graduated', __('Seconday school year graduated'));
        $grid->column('high_school_name', __('High school name'));
        $grid->column('high_school_year_graduated', __('High school year graduated'));
        $grid->column('degree_university_name', __('Degree university name'));
        $grid->column('degree_university_year_graduated', __('Degree university year graduated'));
        $grid->column('masters_university_name', __('Masters university name'));
        $grid->column('masters_university_year_graduated', __('Masters university year graduated'));
        $grid->column('phd_university_name', __('Phd university name'));
        $grid->column('phd_university_year_graduated', __('Phd university year graduated'));
        $grid->column('user_type', __('User type'));
        $grid->column('demo_id', __('Demo id'));
        $grid->column('user_id', __('User id'));
        $grid->column('user_batch_importer_id', __('User batch importer id'));
        $grid->column('school_pay_account_id', __('School pay account id'));
        $grid->column('school_pay_payment_code', __('School pay payment code'));
        $grid->column('given_name', __('Given name'));
        $grid->column('deleted_at', __('Deleted at'));
        $grid->column('marital_status', __('Marital status'));
        $grid->column('verification', __('Verification'));
        $grid->column('current_class_id', __('Current class id'));
        $grid->column('current_theology_class_id', __('Current theology class id'));
        $grid->column('status', __('Status'));
        $grid->column('parent_id', __('Parent id'));
        $grid->column('main_role_id', __('Main role id'));
        $grid->column('stream_id', __('Stream id'));
        $grid->column('account_id', __('Account id'));
        $grid->column('has_personal_info', __('Has personal info'));
        $grid->column('has_educational_info', __('Has educational info'));
        $grid->column('has_account_info', __('Has account info'));
        $grid->column('diploma_school_name', __('Diploma school name'));
        $grid->column('diploma_year_graduated', __('Diploma year graduated'));
        $grid->column('certificate_school_name', __('Certificate school name'));
        $grid->column('certificate_year_graduated', __('Certificate year graduated'));
        $grid->column('company_id', __('Company id'));
        $grid->column('managed_by', __('Managed by'));
        $grid->column('title', __('Title'));
        $grid->column('dob', __('Dob'));
        $grid->column('intro', __('Intro'));
        $grid->column('rate', __('Rate'));
        $grid->column('can_evaluate', __('Can evaluate'));
        $grid->column('work_load_pending', __('Work load pending'));
        $grid->column('work_load_completed', __('Work load completed'));
        $grid->column('belongs_to_company', __('Belongs to company'));
        $grid->column('card_status', __('Card status'));
        $grid->column('card_number', __('Card number'));
        $grid->column('card_balance', __('Card balance'));
        $grid->column('card_accepts_credit', __('Card accepts credit'));
        $grid->column('card_max_credit', __('Card max credit'));
        $grid->column('card_accepts_cash', __('Card accepts cash'));
        $grid->column('is_dependent', __('Is dependent'));
        $grid->column('dependent_status', __('Dependent status'));
        $grid->column('dependent_id', __('Dependent id'));
        $grid->column('card_expiry', __('Card expiry'));
        $grid->column('belongs_to_company_status', __('Belongs to company status'));
        $grid->column('objective', __('Objective'));
        $grid->column('special_qualification', __('Special qualification'));
        $grid->column('career_summary', __('Career summary'));
        $grid->column('present_salary', __('Present salary'));
        $grid->column('expected_salary', __('Expected salary'));
        $grid->column('expected_job_level', __('Expected job level'));
        $grid->column('expected_job_nature', __('Expected job nature'));
        $grid->column('preferred_job_location', __('Preferred job location'));
        $grid->column('preferred_job_category', __('Preferred job category'));
        $grid->column('preferred_job_category_other', __('Preferred job category other'));
        $grid->column('preferred_job_districts', __('Preferred job districts'));
        $grid->column('preferred_job_abroad', __('Preferred job abroad'));
        $grid->column('preferred_job_countries', __('Preferred job countries'));
        $grid->column('has_disability', __('Has disability'));
        $grid->column('is_registered_on_disability', __('Is registered on disability'));
        $grid->column('disability_type', __('Disability type'));
        $grid->column('dificulty_to_see', __('Dificulty to see'));
        $grid->column('dificulty_to_hear', __('Dificulty to hear'));
        $grid->column('dificulty_to_walk', __('Dificulty to walk'));
        $grid->column('dificulty_to_speak', __('Dificulty to speak'));
        $grid->column('dificulty_display_on_cv', __('Dificulty display on cv'));
        $grid->column('country_code', __('Country code'));
        $grid->column('blood_group', __('Blood group'));
        $grid->column('height', __('Height'));
        $grid->column('weight', __('Weight'));
        $grid->column('company_name', __('Company name'));
        $grid->column('company_year_of_establishment', __('Company year of establishment'));
        $grid->column('company_employees_range', __('Company employees range'));
        $grid->column('company_country', __('Company country'));
        $grid->column('company_address', __('Company address'));
        $grid->column('company_district_id', __('Company district id'));
        $grid->column('company_sub_county_id', __('Company sub county id'));
        $grid->column('company_main_category_id', __('Company main category id'));
        $grid->column('company_sub_category_id', __('Company sub category id'));
        $grid->column('company_phone_number', __('Company phone number'));
        $grid->column('company_description', __('Company description'));
        $grid->column('company_trade_license_no', __('Company trade license no'));
        $grid->column('company_website_url', __('Company website url'));
        $grid->column('company__email', __('Company  email'));
        $grid->column('company__phone', __('Company  phone'));
        $grid->column('company_has_accessibility', __('Company has accessibility'));
        $grid->column('company_has_disability_inclusion_policy', __('Company has disability inclusion policy'));
        $grid->column('company_logo', __('Company logo'));
        $grid->column('company_tax_id', __('Company tax id'));
        $grid->column('company_facebook_url', __('Company facebook url'));
        $grid->column('company_linkedin_url', __('Company linkedin url'));
        $grid->column('company_operating_hours', __('Company operating hours'));
        $grid->column('company_certifications', __('Company certifications'));
        $grid->column('company_ownership_type', __('Company ownership type'));
        $grid->column('company_status', __('Company status'));
        $grid->column('is_company', __('Is company'));
        $grid->column('district_id', __('District id'));
        $grid->column('code', __('Code'));
        $grid->column('code_is_sent', __('Code is sent'));
        $grid->column('code_sent_at', __('Code sent at'));

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(User::findOrFail($id));

        $show->field('id', __('Id'));
        $show->field('username', __('Username'));
        $show->field('password', __('Password'));
        $show->field('name', __('Name'));
        $show->field('avatar', __('Avatar'));
        $show->field('remember_token', __('Remember token'));
        $show->field('created_at', __('Created at'));
        $show->field('updated_at', __('Updated at'));
        $show->field('enterprise_id', __('Enterprise id'));
        $show->field('first_name', __('First name'));
        $show->field('last_name', __('Last name'));
        $show->field('date_of_birth', __('Date of birth'));
        $show->field('place_of_birth', __('Place of birth'));
        $show->field('sex', __('Sex'));
        $show->field('home_address', __('Home address'));
        $show->field('current_address', __('Current address'));
        $show->field('phone_number_1', __('Phone number 1'));
        $show->field('phone_number_2', __('Phone number 2'));
        $show->field('email', __('Email'));
        $show->field('nationality', __('Nationality'));
        $show->field('religion', __('Religion'));
        $show->field('spouse_name', __('Spouse name'));
        $show->field('spouse_phone', __('Spouse phone'));
        $show->field('father_name', __('Father name'));
        $show->field('father_phone', __('Father phone'));
        $show->field('mother_name', __('Mother name'));
        $show->field('mother_phone', __('Mother phone'));
        $show->field('languages', __('Languages'));
        $show->field('emergency_person_name', __('Emergency person name'));
        $show->field('emergency_person_phone', __('Emergency person phone'));
        $show->field('national_id_number', __('National id number'));
        $show->field('passport_number', __('Passport number'));
        $show->field('tin', __('Tin'));
        $show->field('nssf_number', __('Nssf number'));
        $show->field('bank_name', __('Bank name'));
        $show->field('bank_account_number', __('Bank account number'));
        $show->field('primary_school_name', __('Primary school name'));
        $show->field('primary_school_year_graduated', __('Primary school year graduated'));
        $show->field('seconday_school_name', __('Seconday school name'));
        $show->field('seconday_school_year_graduated', __('Seconday school year graduated'));
        $show->field('high_school_name', __('High school name'));
        $show->field('high_school_year_graduated', __('High school year graduated'));
        $show->field('degree_university_name', __('Degree university name'));
        $show->field('degree_university_year_graduated', __('Degree university year graduated'));
        $show->field('masters_university_name', __('Masters university name'));
        $show->field('masters_university_year_graduated', __('Masters university year graduated'));
        $show->field('phd_university_name', __('Phd university name'));
        $show->field('phd_university_year_graduated', __('Phd university year graduated'));
        $show->field('user_type', __('User type'));
        $show->field('demo_id', __('Demo id'));
        $show->field('user_id', __('User id'));
        $show->field('user_batch_importer_id', __('User batch importer id'));
        $show->field('school_pay_account_id', __('School pay account id'));
        $show->field('school_pay_payment_code', __('School pay payment code'));
        $show->field('given_name', __('Given name'));
        $show->field('deleted_at', __('Deleted at'));
        $show->field('marital_status', __('Marital status'));
        $show->field('verification', __('Verification'));
        $show->field('current_class_id', __('Current class id'));
        $show->field('current_theology_class_id', __('Current theology class id'));
        $show->field('status', __('Status'));
        $show->field('parent_id', __('Parent id'));
        $show->field('main_role_id', __('Main role id'));
        $show->field('stream_id', __('Stream id'));
        $show->field('account_id', __('Account id'));
        $show->field('has_personal_info', __('Has personal info'));
        $show->field('has_educational_info', __('Has educational info'));
        $show->field('has_account_info', __('Has account info'));
        $show->field('diploma_school_name', __('Diploma school name'));
        $show->field('diploma_year_graduated', __('Diploma year graduated'));
        $show->field('certificate_school_name', __('Certificate school name'));
        $show->field('certificate_year_graduated', __('Certificate year graduated'));
        $show->field('company_id', __('Company id'));
        $show->field('managed_by', __('Managed by'));
        $show->field('title', __('Title'));
        $show->field('dob', __('Dob'));
        $show->field('intro', __('Intro'));
        $show->field('rate', __('Rate'));
        $show->field('can_evaluate', __('Can evaluate'));
        $show->field('work_load_pending', __('Work load pending'));
        $show->field('work_load_completed', __('Work load completed'));
        $show->field('belongs_to_company', __('Belongs to company'));
        $show->field('card_status', __('Card status'));
        $show->field('card_number', __('Card number'));
        $show->field('card_balance', __('Card balance'));
        $show->field('card_accepts_credit', __('Card accepts credit'));
        $show->field('card_max_credit', __('Card max credit'));
        $show->field('card_accepts_cash', __('Card accepts cash'));
        $show->field('is_dependent', __('Is dependent'));
        $show->field('dependent_status', __('Dependent status'));
        $show->field('dependent_id', __('Dependent id'));
        $show->field('card_expiry', __('Card expiry'));
        $show->field('belongs_to_company_status', __('Belongs to company status'));
        $show->field('objective', __('Objective'));
        $show->field('special_qualification', __('Special qualification'));
        $show->field('career_summary', __('Career summary'));
        $show->field('present_salary', __('Present salary'));
        $show->field('expected_salary', __('Expected salary'));
        $show->field('expected_job_level', __('Expected job level'));
        $show->field('expected_job_nature', __('Expected job nature'));
        $show->field('preferred_job_location', __('Preferred job location'));
        $show->field('preferred_job_category', __('Preferred job category'));
        $show->field('preferred_job_category_other', __('Preferred job category other'));
        $show->field('preferred_job_districts', __('Preferred job districts'));
        $show->field('preferred_job_abroad', __('Preferred job abroad'));
        $show->field('preferred_job_countries', __('Preferred job countries'));
        $show->field('has_disability', __('Has disability'));
        $show->field('is_registered_on_disability', __('Is registered on disability'));
        $show->field('disability_type', __('Disability type'));
        $show->field('dificulty_to_see', __('Dificulty to see'));
        $show->field('dificulty_to_hear', __('Dificulty to hear'));
        $show->field('dificulty_to_walk', __('Dificulty to walk'));
        $show->field('dificulty_to_speak', __('Dificulty to speak'));
        $show->field('dificulty_display_on_cv', __('Dificulty display on cv'));
        $show->field('country_code', __('Country code'));
        $show->field('blood_group', __('Blood group'));
        $show->field('height', __('Height'));
        $show->field('weight', __('Weight'));
        $show->field('company_name', __('Company name'));
        $show->field('company_year_of_establishment', __('Company year of establishment'));
        $show->field('company_employees_range', __('Company employees range'));
        $show->field('company_country', __('Company country'));
        $show->field('company_address', __('Company address'));
        $show->field('company_district_id', __('Company district id'));
        $show->field('company_sub_county_id', __('Company sub county id'));
        $show->field('company_main_category_id', __('Company main category id'));
        $show->field('company_sub_category_id', __('Company sub category id'));
        $show->field('company_phone_number', __('Company phone number'));
        $show->field('company_description', __('Company description'));
        $show->field('company_trade_license_no', __('Company trade license no'));
        $show->field('company_website_url', __('Company website url'));
        $show->field('company__email', __('Company  email'));
        $show->field('company__phone', __('Company  phone'));
        $show->field('company_has_accessibility', __('Company has accessibility'));
        $show->field('company_has_disability_inclusion_policy', __('Company has disability inclusion policy'));
        $show->field('company_logo', __('Company logo'));
        $show->field('company_tax_id', __('Company tax id'));
        $show->field('company_facebook_url', __('Company facebook url'));
        $show->field('company_linkedin_url', __('Company linkedin url'));
        $show->field('company_operating_hours', __('Company operating hours'));
        $show->field('company_certifications', __('Company certifications'));
        $show->field('company_ownership_type', __('Company ownership type'));
        $show->field('company_status', __('Company status'));
        $show->field('is_company', __('Is company'));
        $show->field('district_id', __('District id'));
        $show->field('code', __('Code'));
        $show->field('code_is_sent', __('Code is sent'));
        $show->field('code_sent_at', __('Code sent at'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new User());

        $form->textarea('username', __('Username'));
        $form->textarea('password', __('Password'));
        $form->textarea('name', __('Name'));
        $form->textarea('avatar', __('Avatar'));
        $form->textarea('remember_token', __('Remember token'));
        $form->textarea('enterprise_id', __('Enterprise id'));
        $form->textarea('first_name', __('First name'));
        $form->textarea('last_name', __('Last name'));
        $form->textarea('date_of_birth', __('Date of birth'));
        $form->textarea('place_of_birth', __('Place of birth'));
        $form->textarea('sex', __('Sex'));
        $form->textarea('home_address', __('Home address'));
        $form->textarea('current_address', __('Current address'));
        $form->textarea('phone_number_1', __('Phone number 1'));
        $form->textarea('phone_number_2', __('Phone number 2'));
        $form->textarea('email', __('Email'));
        $form->textarea('nationality', __('Nationality'));
        $form->textarea('religion', __('Religion'));
        $form->textarea('spouse_name', __('Spouse name'));
        $form->textarea('spouse_phone', __('Spouse phone'));
        $form->textarea('father_name', __('Father name'));
        $form->textarea('father_phone', __('Father phone'));
        $form->textarea('mother_name', __('Mother name'));
        $form->textarea('mother_phone', __('Mother phone'));
        $form->textarea('languages', __('Languages'));
        $form->textarea('emergency_person_name', __('Emergency person name'));
        $form->textarea('emergency_person_phone', __('Emergency person phone'));
        $form->textarea('national_id_number', __('National id number'));
        $form->textarea('passport_number', __('Passport number'));
        $form->textarea('tin', __('Tin'));
        $form->textarea('nssf_number', __('Nssf number'));
        $form->textarea('bank_name', __('Bank name'));
        $form->textarea('bank_account_number', __('Bank account number'));
        $form->textarea('primary_school_name', __('Primary school name'));
        $form->textarea('primary_school_year_graduated', __('Primary school year graduated'));
        $form->textarea('seconday_school_name', __('Seconday school name'));
        $form->textarea('seconday_school_year_graduated', __('Seconday school year graduated'));
        $form->textarea('high_school_name', __('High school name'));
        $form->textarea('high_school_year_graduated', __('High school year graduated'));
        $form->textarea('degree_university_name', __('Degree university name'));
        $form->textarea('degree_university_year_graduated', __('Degree university year graduated'));
        $form->textarea('masters_university_name', __('Masters university name'));
        $form->textarea('masters_university_year_graduated', __('Masters university year graduated'));
        $form->textarea('phd_university_name', __('Phd university name'));
        $form->textarea('phd_university_year_graduated', __('Phd university year graduated'));
        $form->textarea('user_type', __('User type'));
        $form->textarea('demo_id', __('Demo id'));
        $form->textarea('user_id', __('User id'));
        $form->textarea('user_batch_importer_id', __('User batch importer id'));
        $form->textarea('school_pay_account_id', __('School pay account id'));
        $form->textarea('school_pay_payment_code', __('School pay payment code'));
        $form->textarea('given_name', __('Given name'));
        $form->textarea('marital_status', __('Marital status'));
        $form->textarea('verification', __('Verification'));
        $form->textarea('current_class_id', __('Current class id'));
        $form->textarea('current_theology_class_id', __('Current theology class id'));
        $form->textarea('status', __('Status'));
        $form->textarea('parent_id', __('Parent id'));
        $form->textarea('main_role_id', __('Main role id'));
        $form->textarea('stream_id', __('Stream id'));
        $form->textarea('account_id', __('Account id'));
        $form->textarea('has_personal_info', __('Has personal info'));
        $form->textarea('has_educational_info', __('Has educational info'));
        $form->textarea('has_account_info', __('Has account info'));
        $form->textarea('diploma_school_name', __('Diploma school name'));
        $form->textarea('diploma_year_graduated', __('Diploma year graduated'));
        $form->textarea('certificate_school_name', __('Certificate school name'));
        $form->textarea('certificate_year_graduated', __('Certificate year graduated'));
        $form->textarea('company_id', __('Company id'));
        $form->textarea('managed_by', __('Managed by'));
        $form->textarea('title', __('Title'));
        $form->textarea('dob', __('Dob'));
        $form->textarea('intro', __('Intro'));
        $form->textarea('rate', __('Rate'));
        $form->textarea('can_evaluate', __('Can evaluate'));
        $form->textarea('work_load_pending', __('Work load pending'));
        $form->textarea('work_load_completed', __('Work load completed'));
        $form->textarea('belongs_to_company', __('Belongs to company'));
        $form->textarea('card_status', __('Card status'));
        $form->textarea('card_number', __('Card number'));
        $form->textarea('card_balance', __('Card balance'));
        $form->textarea('card_accepts_credit', __('Card accepts credit'));
        $form->textarea('card_max_credit', __('Card max credit'));
        $form->textarea('card_accepts_cash', __('Card accepts cash'));
        $form->textarea('is_dependent', __('Is dependent'));
        $form->textarea('dependent_status', __('Dependent status'));
        $form->textarea('dependent_id', __('Dependent id'));
        $form->textarea('card_expiry', __('Card expiry'));
        $form->textarea('belongs_to_company_status', __('Belongs to company status'));
        $form->textarea('objective', __('Objective'));
        $form->textarea('special_qualification', __('Special qualification'));
        $form->textarea('career_summary', __('Career summary'));
        $form->textarea('present_salary', __('Present salary'));
        $form->textarea('expected_salary', __('Expected salary'));
        $form->textarea('expected_job_level', __('Expected job level'));
        $form->textarea('expected_job_nature', __('Expected job nature'));
        $form->textarea('preferred_job_location', __('Preferred job location'));
        $form->textarea('preferred_job_category', __('Preferred job category'));
        $form->textarea('preferred_job_category_other', __('Preferred job category other'));
        $form->textarea('preferred_job_districts', __('Preferred job districts'));
        $form->textarea('preferred_job_abroad', __('Preferred job abroad'));
        $form->textarea('preferred_job_countries', __('Preferred job countries'));
        $form->textarea('has_disability', __('Has disability'));
        $form->textarea('is_registered_on_disability', __('Is registered on disability'));
        $form->textarea('disability_type', __('Disability type'));
        $form->textarea('dificulty_to_see', __('Dificulty to see'));
        $form->textarea('dificulty_to_hear', __('Dificulty to hear'));
        $form->textarea('dificulty_to_walk', __('Dificulty to walk'));
        $form->textarea('dificulty_to_speak', __('Dificulty to speak'));
        $form->textarea('dificulty_display_on_cv', __('Dificulty display on cv'));
        $form->textarea('country_code', __('Country code'));
        $form->textarea('blood_group', __('Blood group'));
        $form->textarea('height', __('Height'));
        $form->textarea('weight', __('Weight'));
        $form->textarea('company_name', __('Company name'));
        $form->textarea('company_year_of_establishment', __('Company year of establishment'));
        $form->textarea('company_employees_range', __('Company employees range'));
        $form->textarea('company_country', __('Company country'));
        $form->textarea('company_address', __('Company address'));
        $form->textarea('company_district_id', __('Company district id'));
        $form->textarea('company_sub_county_id', __('Company sub county id'));
        $form->textarea('company_main_category_id', __('Company main category id'));
        $form->textarea('company_sub_category_id', __('Company sub category id'));
        $form->textarea('company_phone_number', __('Company phone number'));
        $form->textarea('company_description', __('Company description'));
        $form->textarea('company_trade_license_no', __('Company trade license no'));
        $form->textarea('company_website_url', __('Company website url'));
        $form->textarea('company__email', __('Company  email'));
        $form->textarea('company__phone', __('Company  phone'));
        $form->text('company_has_accessibility', __('Company has accessibility'))->default('No');
        $form->textarea('company_has_disability_inclusion_policy', __('Company has disability inclusion policy'));
        $form->textarea('company_logo', __('Company logo'));
        $form->textarea('company_tax_id', __('Company tax id'));
        $form->textarea('company_facebook_url', __('Company facebook url'));
        $form->textarea('company_linkedin_url', __('Company linkedin url'));
        $form->textarea('company_operating_hours', __('Company operating hours'));
        $form->textarea('company_certifications', __('Company certifications'));
        $form->textarea('company_ownership_type', __('Company ownership type'));
        $form->textarea('company_status', __('Company status'));
        $form->text('is_company', __('Is company'))->default('No');
        $form->text('district_id', __('District id'));
        $form->text('code', __('Code'));
        $form->text('code_is_sent', __('Code is sent'));
        $form->datetime('code_sent_at', __('Code sent at'))->default(date('Y-m-d H:i:s'));

        return $form;
    }
}
